stage3/qr_messaging/solution/config/routes.rb
Rails.application.routes.draw do
  resources :messages, only: [:show, :new, :create] do
    member do
      get 'preview'
    end
  end

  root 'messages#new'
end

stage3/qr_messaging/solution/app/models/message.rb
class Message < ActiveRecord::Base
  validates :url, :text, presence: true

  def generate_url
    self.url = SecureRandom.hex(28)
  end
end

stage3/qr_messaging/solution/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

stage3/qr_messaging/solution/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :preview]

  # GET /messages/:url
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/new/:url
  def preview
    url = "#{own_ip}:#{request.port}#{message_path(@message.url)}"
    @qr = RQRCode::QRCode.new(url, :level => :h)
  end

  # POST /messages
  def create
    @message = Message.new(message_params)
    @message.generate_url

    respond_to do |format|
      if @message.save
        format.html { redirect_to new_message_path, notice: "Message created. URL: #{@message.url}" }
      else
        format.html { render :new }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find_by(url: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:url, :text)
    end

    def own_ip
      Socket.ip_address_list.find { |ai| ai.ipv4? && !ai.ipv4_loopback? }.ip_address
    end
end

stage3/qr_messaging/solution/app/helpers/application_helper.rb
module ApplicationHelper
end

stage3/qr_messaging/solution/app/helpers/messages_helper.rb
module MessagesHelper
end

stage3/qr_messaging/solution/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QrMessaging</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p id="notice"><%= notice %></p>
<%= yield %>

</body>
</html>

stage3/qr_messaging/solution/app/views/layouts/application.html.slim
doctype html
html
  head
    title QrMessaging
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    p#notice= notice
    = yield

stage3/qr_messaging/solution/app/views/messages/_form.html.slim
= form_for @message do |f|
  - if @message.errors.any?
    #error_explanation
      h2 = "#{pluralize(@message.errors.count, "error")} prohibited this message from being saved:"
      ul
        - @message.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :text
    = f.text_area :text
  .actions = f.submit

stage3/qr_messaging/solution/app/views/messages/new.html.slim
h1 New message

== render 'form'

= link_to 'Back', messages_path

stage3/qr_messaging/solution/app/views/messages/preview.html.slim
p#notice = notice

p
  strong Url:
  = @message.url
p
  strong Text:
  = @message.text
p
  = raw @qr.as_svg

= link_to 'Back', new_message_path

stage3/qr_messaging/solution/app/views/messages/show.html.slim
p#notice = notice

p
  strong Text:
  = @message.text

= link_to 'Back', new_message_path